### ISSUE TITLE
GUI does not start

### ISSUE THREAD

**Issue by fireshaper** [ash47/OmegleMiddleMan#1]
After running "node app.js" in a terminal window I get the following:

    listening on *:3000
    Found the following servers: front1.omegle.com, front4.omegle.com, front6.omegle.com,     front5.omegle.com, front3.omegle.com, front7.omegle.com, front9.omegle.com, front8.omegle.com, front2.omegle.com

**Comment by ash47** [comment]
You're meant to go to 127.0.0.1:3000 to see a GUI

**Comment by ash47** [comment]
In your web browser

**Comment by fireshaper** [comment]
Do I have to have Omegle already running in my browser? Nothing opens in my
browser automatically.

**Comment by ash47** [comment]
I'll have to improve the instructions, you open the app, it tells you it's listening on port 3000, goto your web browser (this was designed for chrome), goto the following website: 127.0.0.1:3000

**Comment by fireshaper** [comment]
OK, yeah, that's the part I'm missing. I'll give it a shot, thanks! And
thanks for writing this, I love MITM apps for omegle.

**Comment by ash47** [comment]
Just checked and it does tell you to use your browser

**Comment by ash47** [comment]
Originally it was written for mitm, but I ended out just switching to it, it's much better at finding people to talk to, it can even filter bots out, to a certain extent. Just keep in mind you can't middle man video (I tried for so long, flash is too shitty)

**Comment by fireshaper** [comment]
I don't think there are any MITM apps for omegle video, it's just too much
of a pain.

**Comment by ash47** [comment]
You can do it with webcam max + manycam, one for each stream, I reverse engineered their protocol, and can stream video to them, and pull the streams, but their is no api to capture the data and feed it else where

**Comment by fireshaper** [comment]
Yeah, I've done something similar in the past, but it's a pain to keep up
since you need more screen resolution and have to copy and paste their text.

**Comment by ash47** [comment]
Anyways, let me know if this works, it also let's you talk to clever bot!, and middle man it
