### ISSUE TITLE
Add a clear chat button

### ISSUE THREAD

**Issue by Agauos** [ash47/OmegleMiddleMan#10]
This thing lags when there's a lot of text. If there could be a clear chat option or some kind of limit I can set that would be great. As it is now I have to close the chat and open another and then put all the tags back in which is annoying

**Comment by ash47** [comment]
You mean to say, you think there should be an option to clear the chat?
Also, what browser?

**Comment by ash47** [comment]
This has been added, let me know if it fixes your lag issue :)
