### ISSUE TITLE
Automatically "Fix searching"

### ISSUE THREAD

**Issue by motatoes** [ash47/OmegleMiddleMan#12]
Is it possible to automatically perform the `fix searching` process when the `Creating a connection` process exceeds a time limit? Its helpful when starting OmegleMiddleMan without being at the computer.

**Comment by ash47** [comment]
How long do you think we should do it?

**Comment by motatoes** [comment]
It usually takes a few seconds to connect to a new stranger so I'd say 60 seconds is a reasonable timeout limit?

**Comment by ash47** [comment]
Happy to take a pull request, but, I am not going to code this.
