### ISSUE TITLE
Feature Suggestion : Gender Recognition

### ISSUE THREAD

**Issue by TheDarkFlame** [ash47/OmegleMiddleMan#14]
I was thinking, it might be possible to recognize genders of the individuals using the image as well as some well-selected heuristics and a learning algorithm (such as a neural network).
OpenCV provides all of the above facilities, and has a java wrapper. 
it might be a little iffy at first, but could be a fun piece to develop

**Comment by ash47** [comment]
Can't access the image stream, there is no api to grab it

**Comment by TheDarkFlame** [comment]
what a bummer. Appreciate the effort
