### ISSUE TITLE
Ignore button

### ISSUE THREAD

**Issue by Yishaqel** [ash47/OmegleMiddleMan#15]
I don't know if it is possible, but there are too many bots videochat section, it would be good to ignore them. Always they seem to have the same image these bots. It would be very useful.

¡Thanks!

**Comment by ash47** [comment]
The trouble is I can't get access to the image feed in flash, there is no
api to read it

**Comment by Yishaqel** [comment]
And you can ignore someone?

**Comment by TheDarkFlame** [comment]
Omegle, buy default, does not connect you to a userID that you have already connected to. Ignoring someone is done by default. 
It is not possible to ignore the adverts because there is no way to detect them.

**Comment by ash47** [comment]
It's not possible to get their user id, additionally the reason you get
them multiple times is that they randomly generate a new Id each time
