### ISSUE TITLE
Adjust ignore bot time

### ISSUE THREAD

**Issue by fredinurta** [ash47/OmegleMiddleMan#16]
hello
Sorry one quick question. I tried to find it, but had no luck. Where can i increase the ignore bot time , say like from 10 seconds to 30 or so. Thanks for the help.

**Comment by ash47** [comment]
https://github.com/ash47/OmegleMiddleMan/blob/master/static/js/client.js#L387

Line 387 in /static/js/client.js:
p.autoDisconnect(client_id, 10000, 30000);

These are the two delays, measured in milliseconds, the first being disconnect if they dont start typing, the second being disconnect if they didnt send a message yet.

I must have missed the notifiction, so, this is 2 months late, but,  better late than never.
