### ISSUE TITLE
Error:  getaddrinfo ENOTFOUND 

### ISSUE THREAD

**Issue by omar1015495** [ash47/OmegleMiddleMan#18]
Hello

I get this message every time i try to connect to somebody. 

Error: ERROR (13:08:28): getaddrinfo ENOTFOUND front5 front5:80

i reinstall everything, and i still get this error.

**Comment by ash47** [comment]
Omegle changed their API. I have just pushed a patch that updates the API in this project, it should work now. Thanks for the notification.
