### ISSUE TITLE
Auto-Disconnect Feature

### ISSUE THREAD

**Issue by kishan2695** [ash47/OmegleMiddleMan#24]
I want to disconnect after like 20-30 seconds no matter what is happening

**Comment by ash47** [comment]
Just edit the code yourself, I'll give you the exact snippet to replace on your local code:

https://github.com/ash47/OmegleMiddleMan/blob/master/static/js/client.js#L1796-L1822

Something like the following should work:

https://pastebin.com/WVEswfF7
