### ISSUE TITLE
Proxy Functionality (or lack thereof)

### ISSUE THREAD

**Issue by mrtostados** [ash47/OmegleMiddleMan#29]
I'd first like to say that this program is super useful. The code you wrote to filter out bots is really good (better than whatever Omegle uses, at least). Unfortunately, Omegle hit me with a "temporary ban" (not quite sure what for). 

Looking at the code, I noticed that there are provisions for proxies to subvert bans and Captchas. Obviously, the code doesn't work---it's 2-year-old test code after all. I'm a complete Java noob, but from what I can tell, most of the code seems serviceable. If I had to guess, the problem is that the event setting the "proxyInfo" is detection of a Captcha (which at this point is likely deprecated), but there doesn't seem to be a corresponding ban-related event. 

I'm mostly curious as to why you never pursued fully implementing that code, which it seems was pretty close to finished 2 years ago. I'm also wondering if you could be convinced to look into dusting it off or give some idea of what might need to be done (short of a complete rewrite) to render it operable.

**Comment by ash47** [comment]
Hey mate, temp ban is easy to bypass, just jump on omegle and do the
captcha, then you're good to go.

I just need to implement it on The app, they changed it recently.

**Comment by ash47** [comment]
Made this more obvious -- it will now tell you about the recaptcha
