### ISSUE TITLE
Video not broadcasting

### ISSUE THREAD

**Issue by tgnf** [ash47/OmegleMiddleMan#3]
It seems that video is not broadcasting to other windows. Could you verify it?

**Comment by ash47** [comment]
You can't broadcast video to other windows -- this is a limitation of flash, I've tried a lot, there is simply no way to get a handle to the webcam data via flash apis :(

**Comment by tgnf** [comment]
I see. Still the best program out there, this is the only one which can capture video. The only suggestion I have is the option to pair up 2 persons into one chat ( like omeglespyx), so the chat feel more naturally. Keep the good work!

**Comment by ash47** [comment]
You can pair people into one chat using the broadcast buttons below, unless
you mean an option that would find two new strangers if one disconnected?

**Comment by tgnf** [comment]
ya, something like a New button will find 2 people and pair them automatically

**Comment by Newgel** [comment]
why was this closed? This feature is not available yet.

**Comment by ash47** [comment]
It's not possible to broadcast video.
