### ISSUE TITLE
No Client ID - Not an issue on omegle's end

### ISSUE THREAD

**Issue by Sgtpanda** [ash47/OmegleMiddleMan#30]
I saw the previous issue about "No client ID allocation" was closed saying it's an Omegle issue, I'm almost certain it isn't.

I can connect fine on my mobile and desktop, but not through OMM. OMM is running on a server in a different location but I can wget the Omegle homepage fine so I don't think I'm IP banned.

Any help? Thanks.

**Comment by ash47** [comment]
It's not something i can reproduce.

When ever i get "no client id allocated" within omm, i get the equivalent
of "unable to connect to servers" on omegle.

It would be worth noting that interests and interest free searching are
part of different queues

It's also no a fair test case if you're connecting from two different
locations to run your tests -- spin up the server locally and test it using
the same ip address and see if you can reproduce.

I'm literally calling the same api end points as the web site, there is no
difference -- there's not much i can do, there's no different way of
calling the apis.

I need solid proof that what you're saying is true, and then i need a copy
of the traffic / a method to reproduce this.

It's not trivial to fix.
