### ISSUE TITLE
Getting a "socket hang up" error when trying to start

### ISSUE THREAD

**Issue by Mcmarc00** [ash47/OmegleMiddleMan#32]

**Comment by Mcmarc00** [comment]
Not very helpful https://imgur.com/cGE5YyU

**Comment by ash47** [comment]
That's pretty helpful -- it's not even finding ANY servers :O

**Comment by ash47** [comment]
Can you run "node --version" in your console and tell me what version it says you have?

**Comment by Mcmarc00** [comment]
v7.2.1 All was fine yesterday and I'm not sure whats changed.

**Comment by ash47** [comment]
Would you please visit the following page and tell me what it says?

http://omegle.com/status?nocache=lol

Just paste the contents here?

**Comment by Mcmarc00** [comment]
`{"count": 12573, "antinudeservers": ["waw3.omegle.com", "waw2.omegle.com", "waw1.omegle.com"], "spyQueueTime": 1.792900013923645, "rtmfp": "rtmfp://p2p.rtmfp.net", "antinudepercent": 1.0, "spyeeQueueTime": 0.3693000078201294, "timestamp": 1528850062.623993, "servers": ["front22", "front15", "front8", "front12", "front7", "front20", "front18", "front16", "front17", "front32", "front13", "front28", "front19", "front3", "front31", "front29", "front6", "front21", "front24", "front26", "front1", "front30", "front23", "front10", "front11", "front14", "front27", "front5", "front9", "front2", "front25", "front4"]}`

**Comment by ash47** [comment]
I just made a commit to make the server selection code more robust -- do you want to pull down a new copy, and see if it's fixed? / Tell me what the console says if it doesnt work?

**Comment by Mcmarc00** [comment]
Exactly the same as before

**Comment by ash47** [comment]
Can you try and update your NodeJS: https://nodejs.org/en/download/current/

Make sure you run node --version to ensure it was actually updated -- let's just cross off the obvious issues if we can...

**Comment by Mcmarc00** [comment]
Node updated fine to v10.4.1 but the issue is still there

**Comment by ash47** [comment]
Ok, I've upgraded it to use TLS -- hopefully that will provide a much more stable connection, let me know if that helped?

**Comment by Mcmarc00** [comment]
Yup that got it working again, thanks very much.

**Comment by ash47** [comment]
Sweet, got a few little improvements there, thanks for the feedback :)
