### ISSUE TITLE
Install.bat and Run.bat automatically closes. 

### ISSUE THREAD

**Issue by stevenlim11277** [ash47/OmegleMiddleMan#43]
I can't run Install.bat and Run.bat. They close as soon as I open it. 

I tried reinstalling NodeJS and your files but it doesn't work. Everything was fine few weeks ago.

**Comment by stevenlim11277** [comment]
My apologies, my cmd doesn't work because of some shitty bitcoin mining virus shit. I deleted them and now it works fine. 

HKEY_CURRENT_USER -
Software -
Microsoft -
Command Processor - AutoRun (deleted)

**Comment by ash47** [comment]
a problem that solves itself? That's my kind of problem!
