### ISSUE TITLE
Suggestion - Video MTIM

### ISSUE THREAD

**Issue by TheDarkFlame** [ash47/OmegleMiddleMan#5]
Instead of having video streams being routed from the MITM, instead redirect the video stream from one user to the next.
Perhaps this is easier said than done, I don't have any javascript experience, so I'm unsure

**Comment by ash47** [comment]
I spent a lot of time on this, I couldn't find any way to read / write to the video streams using flash, all I can do is basically say "use this webcam and stream it to the internet" or "take this stream and display it here", there isn't a low level API to do mitm with

**Comment by TheDarkFlame** [comment]
I think one would have to do some packet sniffing into the RTMP protocol if you wanted to do that, which would likely extend beyond the expertise of javascript...
I remember reading somewhere that omegle uses a form of encryption in their packets, so that may be an issue...
I suppose the best alternative would then be to use another program to stream that section of your screen

**Comment by ash47** [comment]
Yes, I tried to find a nodejs module for that protocol a while back but
didn't really have any luck because it's a flash specific protocol.

**Comment by ash47** [comment]
I guess I'm a lot more experienced now vs when I last tried, in theory I
can use the nodejs rtmp server module, then have my omegle client stream
video to that, then have the server stream the data to omegle, in theory
that should work, also means I can capture the webcam data of all users and
push that back to another stream, aka man in the middle

**Comment by ash47** [comment]
I had a deeper look, they are using the RTMFP, and not RTMP. There isn't any implementations of RTMFP clients in nodejs, so, without spending a huge amount of time reverse engineering, I can't really do this :/ big difference between RTMP and RTMFP :/

**Comment by ash47** [comment]
So, here's the API I am dealing with:

http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/net/NetStream.html

appendBytes(bytes:ByteArray):void
Passes a ByteArray into a NetStream for playout.

Is exactly what I need to push data, however, I can't see anything to read data from the netstream :/

**Comment by TheDarkFlame** [comment]
just going to dump these links here so they don't get lost...

- http://www.adobe.com/devnet/adobe-media-server/articles/p2p_rtmfp_groups.html about half way down there is some information that may be relevant, though the article itself is about setting up P2P stream distribution networks... effectively we are doing this though...
- https://forums.adobe.com/thread/1086947 the comment by Vijay might be useful, it describes connecting to the remote peer and some other stuff I didn't really follow...
- http://help.adobe.com/en_US/FlashPlatform/beta/reference/actionscript/3/flash/net/package-detail.html this is just a level up higher than the API posted in the last comment
- http://stackoverflow.com/questions/2713110/easy-bidirectional-communication-via-p2p-netstream discussion about some properties about when the peer connects... seemed relevant, but I'm not 100% sure I follow
- notes: there seems to be a way to connect, as one would expect. from that, then you need to obtain the peer ID, and then use streamobject.send() to get data somehow (seems kinda intuitive, I suspect I didn't understand that right). Also, there's a lot of talk about MAX 2009... but the links are all dead, and a google search pretty much brings up nothing, finally, searching the documentation in the post above this for the keyword "client" sorta helps... again... not 100% familiar with the protocols, so it may be a goose chase
given that there is a way to distribute using netgroups, I think this should be possible, but it might be messy, and it might be complex...

**Comment by ash47** [comment]
opps, hit enter by mistake XD none of those links were of much use :/

**Comment by ash47** [comment]
Tried this, failed, the APIs simply are not there to perform this kind of attack, sad face.
