### ISSUE TITLE
How do I see other ppl's message? And I can't generate the log.

### ISSUE THREAD

**Issue by lKingslayer** [ash47/OmegleMiddleMan#50]

**Comment by ash47** [comment]
This project is largely unmaintained. The man in the middle is achieved by
opening two chats, and then forwarding the messages from one into the other
using the check boxes that appear.

**Comment by lKingslayer** [comment]
I mean if we are able to see what messages other people send, then it would more fun and useful. Otherwise, it's like talking to the air. Anyway, thanks for your interesting work. And I hope this project can be maintained and continued.

Cheers!

**Comment by ash47** [comment]
You can see what other people send though. I just think you don't
understand the logic.

If you open two chats and forward the messages to each other using the
built in functionality then you're doing exactly that -- you can see two
people chatting.

You can even do a group chat with more than 2 people using this
functionality.

**Comment by lKingslayer** [comment]
I know what you are trying to say. And I went to localhost:3000 in my web browser. I was able to send messages through the window but I couldn't see other people's messages anywhere. There was no feedback or anything. All I can see is that after I sent the message and the icon to the messages turned green. And that's all. I don't know what is the problem here. 

Thanks!

**Comment by ash47** [comment]
Did you press connect? Did you get a match?

https://youtu.be/BaX9uHX6CPg

There is a tutorial for you

**Comment by lKingslayer** [comment]
Thanks, this tutorial is helpful. Yeah, maybe the connection was not good. The stranger's messages just didn't show up. Anyway, I will try again.  

Thank you!

**Comment by lKingslayer** [comment]
It's solved. Thanks for your help.

Cheers!
