### ISSUE TITLE
where do i paste the code to exactly setCameraSize(320, 240, 24, 91)?

### ISSUE THREAD

**Issue by theunkownanon** [ash47/OmegleMiddleMan#59]
hey where do i paste this (setCameraSize(320, 240, 24, 91)) into exactly im kinda of confused anyone please help with specific details

**Comment by GermanJesus-lul** [comment]
The camera function is not working anymore, for omegle changed their protocol and this project is discontinued.

**Comment by ash47** [comment]
I need to do an update to support the new protocol.
