### ISSUE TITLE
Suggestion - make text window a fixed size

### ISSUE THREAD

**Issue by TheDarkFlame** [ash47/OmegleMiddleMan#6]
The chat box dynamically resizes to the content inserted into it.
This means that when conversations become long, the text rapidly drops off of the bottom of the screen.
This is usually OK, as the textbox to enter text is at the bottom.
However, when streaming video, the video remains at the top, whilst the textbox goes to the bottom.

**Comment by ash47** [comment]
I am not sure what you mean?

**Comment by ash47** [comment]
This is an issue with firefox :( it doesn't like my CSS -- works fine in chrome -- will take a look to see if i can fix the CSS easily :/

**Comment by ash47** [comment]
God this took a lot of effort -- firefox, why you so evil?

Should be fixed now :D
