### ISSUE TITLE
Omegle update has broken the ability to connect

### ISSUE THREAD

**Issue by Mcmarc00** [ash47/OmegleMiddleMan#63]
Gets stuck on "Creating a connection..." ever since the latest Omegle update that introduced these checkboxes (https://i.imgur.com/I34LUWH.png) before you can use the site.

**Comment by OmegleMan29** [comment]
They fixed it?

**Comment by deadpool0001** [comment]
still struck on "creating a connection "   can you please suggest the fix

**Comment by ncollens5** [comment]
Same error. Please please please fix

**Comment by fm-123** [comment]
I have an actual fix which I would be willing to share against payment in BTC.

**Comment by ash47** [comment]
This is fixed, do not pay @fm-123  to add 2 characters to the code, it's very poor form to request payment for such a trivial amount of work.

**Comment by ncollens5** [comment]
Dear @ash47 , it still shows as 'connecting'

**Comment by ncollens5** [comment]
http://imgur.com/gallery/mgzLrKP

**Comment by ash47** [comment]
There's no auto update, did you delete your existing copy, download/ clone
the new update, and reinstall + relaunch it?
