### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by ncollens5** [ash47/OmegleMiddleMan#64]
It's not connecting since last week. please update it pleaseeee

**Comment by fm-123** [comment]
I have an actual fix which I would be willing to share against payment in BTC.

**Comment by ash47** [comment]
This is fixed now, please test and confirm.

**Comment by ncollens5** [comment]
Dear @ash47 http://imgur.com/gallery/mgzLrKP
It is stuck at 'Creating connection'

**Comment by ash47** [comment]
There's no auto update, did you delete your existing copy, download/ clone
the new update, and reinstall + relaunch it?

**Comment by ncollens5** [comment]
Yes, it's working now. Thanks @ash47
