### ISSUE TITLE
Software spams chat

### ISSUE THREAD

**Issue by Agauos** [ash47/OmegleMiddleMan#8]
Occasionally the software will take my greeting (little text box next to send button) and just spam it in all of the open chats until I end the chat that glitched out. Sometimes multiple chats glitch out like this. I've even seen it spam the last few messages that were sent. I have not been able to isolate any cause for this, it just happens.

**Comment by ash47** [comment]
Do you have Auto forward thing on, if that's the case and two bots get each
other, they will spam.

**Comment by Agauos** [comment]
Pretty sure that's what happened
