### ISSUE TITLE
'node' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by 6stitch9** [ash47/OmegleMiddleMan#82]
i have node installed and everything, but when I try and open run.bat I get the following in cmd:

A:\OmegleMiddleMan-master\OmegleMiddleMan-master>node app.js
'node' is not recognized as an internal or external command,
operable program or batch file.

A:\OmegleMiddleMan-master\OmegleMiddleMan-master>pause
Press any key to continue . . .

**Comment by 6stitch9** [comment]
also this when i try install.bat:
Please wait, attempting to install...
'npm' is not recognized as an internal or external command,
operable program or batch file.
Please ensure you have installed NodeJS. Download from https://nodejs.org/en/
Press any key to continue . . .

do i need a certain version of it installed? the video you have uses an older version

**Comment by ketchupwater** [comment]
Hi @6stitch9! Normally, a newer version of Node should be fine. It looks like you don't have Node installed, because it can't find the `node` and `npm` commands. Could you try reinstalling node and then restarting your CLI? Alternatively, [restarting Explorer can work or just restart your computer](https://stackoverflow.com/questions/10129505/node-not-recognized-although-successfully-installed).

Let me know if that helped.

**Comment by used2bsane** [comment]
Who are you replying to? Did u get an email from this email address?

**Comment by ketchupwater** [comment]
@used2bsane I don't tunderstand your question - I only answered the question posed in this ticket.

**Comment by matiasvlevi** [comment]
@6stitch9 If you have installed node, it's probably not in your `PATH` environment variable. 

You need to add the path to the `node` executable you just downloaded in the `path` variable.

Here is how you can create/modify an environment variable on windows:
<https://docs.oracle.com/en/database/oracle/machine-learning/oml4r/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0>

**Comment by ash47** [comment]
Please install NodeJS
https://nodejs.org/en/

Please ensure it added to your path:
See first answer: https://stackoverflow.com/questions/27864040/fixing-npm-path-in-windows-8-and-10

Please restart windows to ensure the environment variables are updated.
