### ISSUE TITLE
Connot find module qs

### ISSUE THREAD

**Issue by matyi101** [ash47/OmegleMiddleMan#83]
D:\OmegleMiddleMan-master>node app.js
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'qs'
Require stack:
- D:\OmegleMiddleMan-master\omegle.js
- D:\OmegleMiddleMan-master\app.js
←[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:778:27)←[39m
←[90m    at Module.require (node:internal/modules/cjs/loader:1005:19)←[39m
←[90m    at require (node:internal/modules/cjs/helpers:102:18)←[39m
    at Object.<anonymous> (D:\OmegleMiddleMan-master\omegle.js:7:10)
←[90m    at Module._compile (node:internal/modules/cjs/loader:1105:14)←[39m
←[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:981:32)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:822:12)←[39m
←[90m    at Module.require (node:internal/modules/cjs/loader:1005:19)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
    ←[32m'D:\\OmegleMiddleMan-master\\omegle.js'←[39m,
    ←[32m'D:\\OmegleMiddleMan-master\\app.js'←[39m
  ]
}

D:\OmegleMiddleMan-master>pause
Press any key to continue . . .

**Comment by ItsMe-TJ** [comment]
There's a new version of the app being developed.

check it out at middleman.net :)

**Comment by ash47** [comment]
Please run the install.bat file.
