### ISSUE TITLE
When can i buy premium 

### ISSUE THREAD

**Issue by mountaincastle47** [ash47/OmegleMiddleMan#85]
And is it a one time purchase or subscription

**Comment by ash47** [comment]
I feel like the product needs more polish, I don't feel comfortable selling premium access right now, and the structure / cost isn't defined right now. You can't buy premium right now.

**Comment by mountaincastle47** [comment]
> I feel like the product needs more polish, I don't feel comfortable selling premium access right now, and the structure / cost isn't defined right now. You can't buy premium right now.

Aight then
