### ISSUE TITLE
how to select region?

### ISSUE THREAD

**Issue by mountaincastle47** [ash47/OmegleMiddleMan#87]
????

**Comment by ketchupwater** [comment]
It is not possible to select a region in Omegle, nor in OmegleMiddleman. However, you can choose your preferred language. 
In `settings.json`, set `defaultLanguage` to your preferred language code, e.g. "fr" for French, "de" for German, etc. Then, save the file and restart the node app.

**Comment by mountaincastle47** [comment]
> It is not possible to select a region in Omegle, nor in OmegleMiddleman. However, you can choose your preferred language. In `settings.json`, set `defaultLanguage` to your preferred language code, e.g. "fr" for French, "de" for German, etc. Then, save the file and restart the node app.

And where is this settings.json? I don't see it

**Comment by ash47** [comment]
There's a sample file, you should copy that sample settings file and call
it "settings.JSON", I can see why that's confusing

**Comment by ketchupwater** [comment]
There is a `settings.json` file in the root directory. https://github.com/ash47/OmegleMiddleMan/blob/master/settings.json
