### ISSUE TITLE
Stuck on creating an connection

### ISSUE THREAD

**Issue by LilCrabby** [ash47/OmegleMiddleMan#88]
The program was working but now all of the sudden it is stuck on creating an connection... 
I tried restarting the program and my pc but it keeps saying creating a connection  ...

**Comment by ncollens5** [comment]
Hi @ash47 please advise the solution

**Comment by ash47** [comment]
Can confirm that I see the same thing on my side, will look into this shortly.

**Comment by ncollens5** [comment]
Any update?

**Comment by ash47** [comment]
Please pull latest version and install dependencies again. I have put a fix that will automatically calculate and add the cc field and the other changes that were required.
