### ISSUE TITLE
Stuck on Creating a connection.......

### ISSUE THREAD

**Issue by mnd33p** [ash47/OmegleMiddleMan#89]
Hi there ,
from last two days it stuck on "Creating a connection...", trying to re install but not fix.Please look into this.
Thanks

**Comment by ncollens5** [comment]
Same problem. @ash47 Admin kindly look into it

**Comment by ash47** [comment]
Can confirm I get the same issue, i'll look into this shortly, thanks for bringing this to my attention :)

**Comment by ncollens5** [comment]
> Can confirm I get the same issue, i'll look into this shortly, thanks for bringing this to my attention :)

![Screenshot_20221012-122205](https://user-images.githubusercontent.com/85629303/195270931-01a85619-b41c-4ab1-87ef-6b145509e535.jpg)
Could be due to the new Omegle restrictions on the Omegle home page
