### ISSUE TITLE
Proxies don't work

### ISSUE THREAD

**Issue by Agauos** [ash47/OmegleMiddleMan#9]
Says each proxy is broken, software is up to date.

**Comment by ash47** [comment]
How many did you try?

**Comment by ash47** [comment]
Not really much I can do -- just disable the "bypass captcha" feature -- this was something i just wanted to experiment with, it picks a random proxy from a list, there is no guarentee it will pick a working proxy :/

**Comment by Agauos** [comment]
Not a big deal, was just letting you know :)
