### ISSUE TITLE
recaptcha issue 

### ISSUE THREAD

**Issue by nepal4972** [ash47/OmegleMiddleMan#92]
Saying: Localhost is not in the list of [supported domains](https://developers.google.com/recaptcha/docs/faq#localhost_support) for this site key.

How to fix this issue

**Comment by ncollens5** [comment]
Where does it show that error?

**Comment by ash47** [comment]
Go to omegle.com, do the recapture, and then try. If you are getting it on every single chat, you're out of luck for now.
