### ISSUE TITLE
Stuck on creating a connection...

### ISSUE THREAD

**Issue by OmegleGuy** [ash47/OmegleMiddleMan#97]

**Comment by waker1771** [comment]
Likewise - I have the same problem here.

**Comment by LilCrabby** [comment]
@ash47 any idea on how to fix? I have had the same problem for a few weeks now

**Comment by ash47** [comment]
Please pull latest version and install dependencies again. I have put a fix that will automatically calculate and add the cc field and the other changes that were required.
