### ISSUE TITLE
recaptcha2,t3

### ISSUE THREAD

**Issue by satan971** [ash47/OmegleMiddleMan#98]
there has been a recaptcha update. the new value is `recaptcha2,t3` but even after updating it, it doesnt seem to work. I checked other variables. Cant seem to find whats the exact issue apart from the recaptcha update. Also just out of curiosity, why are they changing this value everytime? is it a map from this value to the T&C of omegle.com?

**Comment by satan971** [comment]
![image](https://user-images.githubusercontent.com/115694528/209415258-1cc68492-3f5a-41e9-9426-2aaf55b30f09.png)

**Comment by OmegleGuy** [comment]
Hey bro, did you find a solution to work?

**Comment by satan971** [comment]
@ash47

**Comment by satan971** [comment]
@ash47 can you please fix it? or give some hint on how to debug it

**Comment by satan971** [comment]
![image](https://user-images.githubusercontent.com/115694528/210171459-8f603faf-2f2a-4de2-bcea-9b9e8e3adb4f.png)
I have traced the problem to the start request.

**Comment by satan971** [comment]
they have added a cc field. but I cant figure out how is it being generated. Hardcoding its value seems to solve the problem. but Im assuming this value would be invalid after a while.

**Comment by gitcoder303** [comment]
@satan971 Can you tell how to hardcode the value? I am new to this stuff.

**Comment by waker1771** [comment]
> they have added a cc field. but I cant figure out how is it being generated. Hardcoding its value seems to solve the problem. but Im assuming this value would be invalid after a while.

I would also like to know how you hardcoded this value!

**Comment by satan971** [comment]
![image](https://user-images.githubusercontent.com/115694528/210719282-dbc684f9-8243-4e5b-baf0-a81665dd9b0c.png)
open a tab in browser. open inspect page using ctrl + I and go to omegle.com. You will see this url, under network tab. In headers you can find the cc value.

**Comment by Mcmarc00** [comment]
@satan971 Can you give a step by step on how you fixed it, what files you had to update specifically?

**Comment by gitcoder303** [comment]
@satan971 I would also like to know what files you updated.

**Comment by satan971** [comment]
![image](https://user-images.githubusercontent.com/115694528/211059597-8ecc3cf3-9cf5-4c5a-aa9f-706423448c4d.png)
In omegle.js, update caps and add cc. you can get the value of cc using the above method.

**Comment by Mcmarc00** [comment]
@satan971 Just tried that but it won't start

                cc: 'c594c15e6a18dcd7c764c2e93e6dc7dc3fc59ce9'
                ^^

SyntaxError: Unexpected identifier
←[90m    at Object.compileFunction (node:vm:352:18)←[39m
←[90m    at wrapSafe (node:internal/modules/cjs/loader:1033:15)←[39m
←[90m    at Module._compile (node:internal/modules/cjs/loader:1069:27)←[39m
←[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:981:32)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:822:12)←[39m
←[90m    at Module.require (node:internal/modules/cjs/loader:1005:19)←[39m
←[90m    at require (node:internal/modules/cjs/helpers:102:18)←[39m
    at Object.<anonymous> (C:\Users\[redacted]\Desktop\OmegleMiddleMan-master\OmegleMiddleMan-master\app.js:1:14)
←[90m    at Module._compile (node:internal/modules/cjs/loader:1105:14)←[39m

**Comment by satan971** [comment]
did u update recaptcha

**Comment by satan971** [comment]
https://discord.gg/eEvraVFr
join here and lemme know what issue r u facing

**Comment by waker1771** [comment]
> did u update recaptcha

I'm also getting the identical error. There's no cc field there by default.

**Comment by ash47** [comment]
Please pull latest version and install dependencies again. I have put a fix that will automatically calculate and add the cc field and the other changes that were required.
